# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: otrokov\kbot
  tag: "v1.0.9-1181d7f"
  arch: amd64
secret:
  name: "kbot"
  tokenname: "TELE_TOKEN"
  tokenkey: "token"
securityContext:
  privileged: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
