apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
      containers:
      - name: demo-job
        image: nginx:latest
        command: ["echo", "Hello World!"]
      restartPolicy: Never
  backoffLimit: 4