apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-project
  template:
    metadata:
      labels:
        app: demo-project
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80
      - name: redis
        image: redis:5.0
        ports:
        - containerPort: 6379