apiVersion: v1
kind: Pod
metadata:
  name: demo-project
spec:
  containers:
  - name: demo-project
    image: demo-project:latest
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3