apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-project
  template:
    metadata:
      labels:
        app: demo-project
    spec:
      containers:
      - name: demo-project
        image: demo-project:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-project
spec:
  selector:
    app: demo-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80