name: KBOT_CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ububntu-latest
    
    
    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: make test
